apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sla-raft-node0
spec:
  template:
    spec:
      containers:
      - name: network
        imagePullPolicy: IfNotPresent
      - name: consensus
        imagePullPolicy: IfNotPresent
      - name: executor
        imagePullPolicy: IfNotPresent
      - name: storage
        imagePullPolicy: IfNotPresent
      - name: controller
        imagePullPolicy: IfNotPresent
      - name: crypto
        imagePullPolicy: IfNotPresent
