apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sla-raft-node0
spec:
  template:
    spec:
      containers:
      - name: network
        livenessProbe:
          exec:
            command:
            - grpc-health-probe
            - -addr=localhost:50000
          initialDelaySeconds: 30
          periodSeconds: 10
      - name: consensus
        livenessProbe:
          exec:
            command:
            - grpc-health-probe
            - -addr=localhost:50001
          initialDelaySeconds: 30
          periodSeconds: 10
      - name: executor
        livenessProbe:
          exec:
            command:
            - grpc-health-probe
            - -addr=localhost:50002
          initialDelaySeconds: 30
          periodSeconds: 10
      - name: storage
        livenessProbe:
          exec:
            command:
            - grpc-health-probe
            - -addr=localhost:50003
          initialDelaySeconds: 30
          periodSeconds: 10
      - name: controller
        livenessProbe:
          exec:
            command:
            - grpc-health-probe
            - -addr=localhost:50004
          initialDelaySeconds: 60
          periodSeconds: 10
