account = "ea0345ad8c8c1c5278b52fb2e8042c9442ed1a90"
enable_metrics = true
is_danger = false
log_level = "info"
network_listen_port = 40000

[grpc_ports]
consensus_port = 50001
controller_port = 50004
crypto_port = 50005
executor_port = 50002
network_port = 50000
storage_port = 50003

[metrics_ports]
consensus_metrics_port = 60001
controller_metrics_port = 60004
crypto_metrics_port = 60005
executor_metrics_port = 60002
network_metrics_port = 60000
storage_metrics_port = 60003

