stage = 'Finalize'

[[micro_service_list]]
image = 'network_zenoh'
tag = 'v6.6.1'

[[micro_service_list]]
image = 'consensus_bft'
tag = 'v6.6.1'

[[micro_service_list]]
image = 'executor_evm'
tag = 'v6.6.1'

[[micro_service_list]]
image = 'storage_rocksdb'
tag = 'v6.6.1'

[[micro_service_list]]
image = 'controller'
tag = 'v6.6.1'

[[micro_service_list]]
image = 'crypto_sm'
tag = 'v6.6.1'

[[node_network_address_list]]
cluster = 'k8s'
domain = 'node0'
host = 'localhost'
port = 40000
svc_port = 40000

[[node_network_address_list]]
cluster = 'k8s'
domain = 'node1'
host = 'localhost'
port = 40001
svc_port = 40000

[[node_network_address_list]]
cluster = 'k8s'
domain = 'node2'
host = 'localhost'
port = 40002
svc_port = 40000

[[node_network_address_list]]
cluster = 'k8s'
domain = 'node3'
host = 'localhost'
port = 40003
svc_port = 40000

[[node_network_address_list]]
cluster = 'k8s'
domain = 'node4'
host = 'localhost'
port = 40004
svc_port = 40000

[genesis_block]
prevhash = '0x0000000000000000000000000000000000000000000000000000000000000000'
timestamp = 1666343491879

[system_config]
admin = '9bab5858df4a9e84ff3958884a01a4fce5e07edb'
block_interval = 3
block_limit = 100
chain_id = '16fd6e0196d12e7e9ed4e9b7e2b891102e05bb13ebce23472c00791b6688f13f'
quota_limit = 1073741824
validators = [
    'a846353e9a316ef97107bb9b01dba562e4ef99fb',
    'eaa32f28b55c27e443d49c6aec7e01087da27d9c',
    'dced1be50c08bb86678910bd0ed4d92175d9141b',
    '3f5b28782b4e5ce691b1ddb60053c1f2a228c9aa',
]
version = 0

