apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/chain-name: sla-bft
    app.kubernetes.io/chain-node: sla-bft-node1
  name: sla-bft-node1
spec:
  ports:
  - name: network
    port: 40000
    protocol: UDP
    targetPort: 40000
  - name: rpc
    port: 50004
    protocol: TCP
    targetPort: 50004
  - name: call
    port: 50002
    protocol: TCP
    targetPort: 50002
  selector:
    app.kubernetes.io/chain-name: sla-bft
    app.kubernetes.io/chain-node: sla-bft-node1
  type: ClusterIP
