stage = 'Finalize'

[[micro_service_list]]
image = 'network_zenoh'
tag = 'v6.6.3'

[[micro_service_list]]
image = 'consensus_bft'
tag = 'v6.6.3'

[[micro_service_list]]
image = 'executor_evm'
tag = 'v6.6.3'

[[micro_service_list]]
image = 'storage_rocksdb'
tag = 'v6.6.3'

[[micro_service_list]]
image = 'controller'
tag = 'v6.6.3'

[[micro_service_list]]
image = 'crypto_sm'
tag = 'v6.6.3'

[[node_network_address_list]]
cluster = 'k8s'
domain = 'node0'
host = 'localhost'
port = 40000
svc_port = 40000

[[node_network_address_list]]
cluster = 'k8s'
domain = 'node1'
host = 'localhost'
port = 40001
svc_port = 40000

[[node_network_address_list]]
cluster = 'k8s'
domain = 'node2'
host = 'localhost'
port = 40002
svc_port = 40000

[[node_network_address_list]]
cluster = 'k8s'
domain = 'node3'
host = 'localhost'
port = 40003
svc_port = 40000

[[node_network_address_list]]
cluster = 'k8s'
domain = 'node4'
host = 'localhost'
port = 40004
svc_port = 40000

[genesis_block]
prevhash = '0x0000000000000000000000000000000000000000000000000000000000000000'
timestamp = 1667199054829

[system_config]
admin = '9bab5858df4a9e84ff3958884a01a4fce5e07edb'
block_interval = 3
block_limit = 100
chain_id = '16fd6e0196d12e7e9ed4e9b7e2b891102e05bb13ebce23472c00791b6688f13f'
quota_limit = 1073741824
validators = [
    '62d600c7f68e8d239350e37c515abd565cded2cf',
    '8f4a1df62be9ebb8ae07ba22a25808cd4ad89fb1',
    'cb34cf78489a17205529113b0df10b8080e5259e',
    'e49d3471b4b021be1fde14d44ee73e2cbe123f21',
]
version = 0

