account = 'eaa32f28b55c27e443d49c6aec7e01087da27d9c'
enable_metrics = true
log_level = 'info'
network_listen_port = 40000

[grpc_ports]
consensus_port = 50001
controller_port = 50004
crypto_port = 50005
executor_port = 50002
network_port = 50000
storage_port = 50003

[metrics_ports]
consensus_metrics_port = 60001
controller_metrics_port = 60004
crypto_metrics_port = 60005
executor_metrics_port = 60002
network_metrics_port = 60000
storage_metrics_port = 60003

