account = "c87e13e9bd31899d0dfea5149bb524b14a02375c"
enable_metrics = true
is_danger = false
log_level = "info"
network_listen_port = 40000

[cloud_storage]
access_key_id = ""
bucket = ""
endpoint = ""
root = ""
secret_access_key = ""
service_type = ""

[grpc_ports]
consensus_port = 50001
controller_port = 50004
executor_port = 50002
network_port = 50000
storage_port = 50003

[metrics_ports]
consensus_metrics_port = 60001
controller_metrics_port = 60004
executor_metrics_port = 60002
network_metrics_port = 60000
storage_metrics_port = 60003

