account = "f461f9efba8ac00d1783df863894f557a1e9893f"
enable_metrics = true
is_danger = false
jaeger_agent_endpoint = "jaeger.tracing.svc:6831"
log_level = "info"
network_listen_port = 40000

[grpc_ports]
consensus_port = 50001
controller_port = 50004
crypto_port = 50005
executor_port = 50002
network_port = 50000
storage_port = 50003

[metrics_ports]
consensus_metrics_port = 60001
controller_metrics_port = 60004
crypto_metrics_port = 60005
executor_metrics_port = 60002
network_metrics_port = 60000
storage_metrics_port = 60003

