apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sla-overlord-node2
spec:
  template:
    spec:
      containers:
      - name: network
        resources:
          limits:
            cpu: 4000m
            memory: 8192Mi
          requests:
            cpu: 10m
            memory: 32Mi
      - name: consensus
        resources:
          limits:
            cpu: 4000m
            memory: 8192Mi
          requests:
            cpu: 10m
            memory: 32Mi
      - name: executor
        resources:
          limits:
            cpu: 4000m
            memory: 8192Mi
          requests:
            cpu: 10m
            memory: 32Mi
      - name: storage
        resources:
          limits:
            cpu: 4000m
            memory: 8192Mi
          requests:
            cpu: 10m
            memory: 32Mi
      - name: controller
        resources:
          limits:
            cpu: 4000m
            memory: 8192Mi
          requests:
            cpu: 10m
            memory: 32Mi
