[network_zenoh]
ca_cert = """
-----BEGIN CERTIFICATE-----\r
MIIBZzCCAQ6gAwIBAgIIYbDhARtcH30wCgYIKoZIzj0EAwIwHzEQMA4GA1UECgwH\r
Q0lUQUh1YjELMAkGA1UEAxMCQ0EwIBcNNzUwMTAxMDAwMDAwWhgPNDA5NjAxMDEw\r
MDAwMDBaMB8xEDAOBgNVBAoMB0NJVEFIdWIxCzAJBgNVBAMTAkNBMFkwEwYHKoZI\r
zj0CAQYIKoZIzj0DAQcDQgAE6KklnxT7ovUXCQHube9spKXe+RPW7SBVXyWiQKSA\r
j6PaRGC6Mnx8vwg4hu0M9aHLT3o5UW66ySyOawrwQiQIP6MyMDAwHQYDVR0OBBYE\r
FH0fXBsB4bBhaFkC7kCRkGNOX5RgMA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0E\r
AwIDRwAwRAIgErCy1bfz4xh8RGZ43VzOZRsJGiR0b5C2aivOhBtFR98CIDOoY794\r
azqy9Jzfc0iJbXN4hzUzYBWgpNWfID9bNdLO\r
-----END CERTIFICATE-----\r
"""
cert = """
-----BEGIN CERTIFICATE-----\r
MIIBaDCCAQ6gAwIBAgIJAJDZv8a9TUI8MAoGCCqGSM49BAMCMB8xEDAOBgNVBAoM\r
B0NJVEFIdWIxCzAJBgNVBAMTAkNBMCAXDTc1MDEwMTAwMDAwMFoYDzQwOTYwMTAx\r
MDAwMDAwWjAvMRAwDgYDVQQKDAdDSVRBSHViMRswGQYDVQQDExJzbGEtb3Zlcmxv\r
cmQtbm9kZTEwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAS2OfF+C1LpruworEW9\r
XtkVX6CII6Xbqc0qugCNokB8u457KXyhSEn8Qt/zdscjL+vTBsU4BCZruKvmtjMd\r
/WdBoyEwHzAdBgNVHREEFjAUghJzbGEtb3ZlcmxvcmQtbm9kZTEwCgYIKoZIzj0E\r
AwIDSAAwRQIgEVp+lcK8U/CnK/lmDQkqgaEpiOu04PHAesQF29/G51YCIQDeU2Eh\r
WQtOk1g/2/S2r78KSLdy9Qy8SDzaZlZykqYVKA==\r
-----END CERTIFICATE-----\r
"""
chain_id = "d00da2a44f0b3d12111a7bfd71db25fd77a765493d6a4c9e66717d743e2ebbbe"
domain = "sla-overlord-node1"
enable_metrics = true
grpc_port = 50000
metrics_port = 60000
node_address = "/mnt/node_address"
port = 40000
priv_key = """
-----BEGIN PRIVATE KEY-----\r
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg2w/v62spwisd6zIT\r
jfzpPIx5DTs+mvF03vApgbVWpa2hRANCAAS2OfF+C1LpruworEW9XtkVX6CII6Xb\r
qc0qugCNokB8u457KXyhSEn8Qt/zdscjL+vTBsU4BCZruKvmtjMd/WdB\r
-----END PRIVATE KEY-----\r
"""
protocol = "quic"
validator_address = "/mnt/validator_address"

[[network_zenoh.modules]]
hostname = "127.0.0.1"
module_name = "consensus"
port = 50001

[[network_zenoh.modules]]
hostname = "127.0.0.1"
module_name = "controller"
port = 50004

[[network_zenoh.peers]]
domain = "sla-overlord-node0"
port = 40000
protocol = "quic"

[[network_zenoh.peers]]
domain = "sla-overlord-node2"
port = 40000
protocol = "quic"

[[network_zenoh.peers]]
domain = "sla-overlord-node3"
port = 40000
protocol = "quic"

[[network_zenoh.peers]]
domain = "sla-overlord-node4"
port = 40000
protocol = "quic"

[network_zenoh.log_config]
filter = "info"
max_level = "info"
service_name = "network"

[consensus_overlord]
consensus_port = 50001
controller_port = 50004
domain = "sla-overlord-node1"
enable_metrics = true
metrics_port = 60001
network_port = 50000

[consensus_overlord.log_config]
filter = "info"
max_level = "info"
service_name = "consensus"

[executor_evm]
domain = "sla-overlord-node1"
enable_metrics = true
executor_port = 50002
metrics_port = 60002

[executor_evm.log_config]
filter = "info"
max_level = "info"
service_name = "executor"

[storage_opendal]
domain = "sla-overlord-node1"
enable_metrics = true
metrics_port = 60003
storage_port = 50003

[storage_opendal.cloud_storage]
access_key_id = ""
bucket = ""
endpoint = ""
root = ""
secret_access_key = ""
service_type = ""

[storage_opendal.log_config]
filter = "info"
max_level = "info"
service_name = "storage"

[genesis_block]
prevhash = "0x0000000000000000000000000000000000000000000000000000000000000000"
timestamp = 1677225735317

[system_config]
admin = "9bab5858df4a9e84ff3958884a01a4fce5e07edb"
block_interval = 3
block_limit = 100
chain_id = "d00da2a44f0b3d12111a7bfd71db25fd77a765493d6a4c9e66717d743e2ebbbe"
quota_limit = 1073741824
validators = [
    "865bb0941877571820ea99f0e72398d6173655b7684a94598518b71d17a5f35f170a10c6a76a8df5c9c6113f8db4a3d9",
    "925a72bceb7f5ebaaf0f50ab525a1967fc48bc113795ddad2ae6d472d073234cd68d9837375d808a0bc6d1aa16d4d6e5",
    "810a1bbbb3d300498f777502c1d62d0da074b849a24f77ae247f7d73c0978916c9cfd58dde6b8fc09a3d04cbd8f1cfb6",
    "928404a9b72168d138cca6719a740026a4fcd617eea69bf243fb3e0f5b6a5b2d9ab83ccb8fac7e14a069ed3f1ac5618b",
]
version = 0

[controller]
consensus_port = 50001
controller_port = 50004
domain = "sla-overlord-node1"
enable_metrics = true
executor_port = 50002
is_danger = false
metrics_port = 60004
network_port = 50000
node_address = "/mnt/node_address"
storage_port = 50003
validator_address = "/mnt/validator_address"

[controller.log_config]
filter = "info"
max_level = "info"
service_name = "controller"

