account = "5435a513062b528415a0502e9e1f0a7f16a53451"
enable_metrics = true
enable_tx_persistence = false
is_danger = false
log_level = "info"

[cloud_storage]
access_key_id = ""
bucket = ""
endpoint = ""
region = ""
root = ""
secret_access_key = ""
service_type = ""

[exporter]
base_path = ""
chain_name = "sla-overlord"

[grpc_ports]
consensus_port = 50001
controller_port = 50004
executor_port = 50002
network_port = 50000
storage_port = 50003

[metrics_ports]
consensus_metrics_port = 60001
controller_metrics_port = 60004
executor_metrics_port = 60002
network_metrics_port = 60000
storage_metrics_port = 60003

