apiVersion: v1
kind: ConfigMap
binaryData:
  private_key: MTExYjhhMTVjMjc5OGRmZmNiZWE4Y2MyYmYwOGEyZjdjMzg0MzRmYzdlNzM2MDdiZjc2N2ZlMGVlNzU1ODkwOQ==
data:
  node_address: d5999f3639d735c75b86098d35b563d66bbafa18
  validator_address: a9d27b8d0e69afe3eb9162c81c5ecbf5342c1fa96a7620dc73a0a42be9324dbddf9faa5f9e6d67581f97cac0002f03fa
metadata:
  labels:
    app.kubernetes.io/chain-name: sla-overlord
    app.kubernetes.io/chain-node: sla-overlord-node3
  name: sla-overlord-node3-account
