apiVersion: v1
kind: ConfigMap
binaryData:
  private_key: NDFjNTQzODdlYjdlNWIwNGRlYjcyMzQyMGVhNTE3OWQ3NjQyOTA3OTBjZjk1MzJiZGZkYWM4MThiZjk3YmJhYQ==
data:
  node_address: 1ea67cd2df9c233b0207f91c94ae9baf12ec71c6
  validator_address: ad00111f0723923b61075bf9f90d4ab7c7a1a2e6e0c1407f80dafbee78a6ea0425767f7a9922922f2c6445c236d361ad
metadata:
  labels:
    app.kubernetes.io/chain-name: sla-overlord
    app.kubernetes.io/chain-node: sla-overlord-node4
  name: sla-overlord-node4-account
