[network_zenoh]
ca_cert = """
-----BEGIN CERTIFICATE-----\r
MIIBajCCAQ+gAwIBAgIJAKiVSikO5DylMAoGCCqGSM49BAMCMB8xEDAOBgNVBAoM\r
B0NJVEFIdWIxCzAJBgNVBAMTAkNBMCAXDTc1MDEwMTAwMDAwMFoYDzQwOTYwMTAx\r
MDAwMDAwWjAfMRAwDgYDVQQKDAdDSVRBSHViMQswCQYDVQQDEwJDQTBZMBMGByqG\r
SM49AgEGCCqGSM49AwEHA0IABDbkfoT24l7BffL/4K3Pdv2bcvdUhtkr2y//I6V3\r
KUy/PRicZYR24VU1a5Y8nBa9E0cHGNgnNCTiJoU+EvXGYCGjMjAwMB0GA1UdDgQW\r
BBSlPOQOKUqVqPQm+qv/5Y0DClT87DAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49\r
BAMCA0kAMEYCIQCLbktpiWjAA0C/MEqFnwr9zRNiDkoNJ2oNYH39vHCi3wIhAOvS\r
XxeRdfRUT2jxeAHwcp7AYE0ijAqc1VJAdsuDLk/6\r
-----END CERTIFICATE-----\r
"""
cert = """
-----BEGIN CERTIFICATE-----\r
MIIBYTCCAQagAwIBAgIJAJmIjNmkdYF3MAoGCCqGSM49BAMCMB8xEDAOBgNVBAoM\r
B0NJVEFIdWIxCzAJBgNVBAMTAkNBMCAXDTc1MDEwMTAwMDAwMFoYDzQwOTYwMTAx\r
MDAwMDAwWjArMRAwDgYDVQQKDAdDSVRBSHViMRcwFQYDVQQDEw5zbGEtcmFmdC1u\r
b2RlMTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABNHQ8ohh3c63rBsxN487seID\r
0tNtROg4Sl+V0i0WL4j0hUn41ABquz0hm0fPitkl+ZiFaKjiBDEFpPr8t4Fv57Cj\r
HTAbMBkGA1UdEQQSMBCCDnNsYS1yYWZ0LW5vZGUxMAoGCCqGSM49BAMCA0kAMEYC\r
IQDkmN11j48aXMW0/WDkKApt5BnEMdOsElhOc3EPLdfuvQIhAN9Zh6+qYrxex78M\r
0UfdmFX/NVGx/y16mtewYb6laX88\r
-----END CERTIFICATE-----\r
"""
chain_id = 'c57bf69f92e8a473ae58582fbf3dc547e1e78c3442bb4bf3313b7005b4163466'
domain = 'sla-raft-node1'
enable_metrics = true
grpc_port = 50000
metrics_port = 60000
node_address = '/mnt/node_address'
port = 40000
priv_key = """
-----BEGIN PRIVATE KEY-----\r
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgCSm4NZxdAAlvmuJf\r
x7D8wJG6oifqmKL6c0kdK59FRmGhRANCAATR0PKIYd3Ot6wbMTePO7HiA9LTbUTo\r
OEpfldItFi+I9IVJ+NQAars9IZtHz4rZJfmYhWio4gQxBaT6/LeBb+ew\r
-----END PRIVATE KEY-----\r
"""
protocol = 'quic'
validator_address = '/mnt/validator_address'

[[network_zenoh.modules]]
hostname = '127.0.0.1'
module_name = 'consensus'
port = 50001

[[network_zenoh.modules]]
hostname = '127.0.0.1'
module_name = 'controller'
port = 50004

[[network_zenoh.peers]]
domain = 'sla-raft-node0'
port = 40000
protocol = 'quic'

[[network_zenoh.peers]]
domain = 'sla-raft-node2'
port = 40000
protocol = 'quic'

[[network_zenoh.peers]]
domain = 'sla-raft-node3'
port = 40000
protocol = 'quic'

[consensus_raft]
controller_port = 50004
enable_metrics = true
grpc_listen_port = 50001
metrics_port = 60001
network_port = 50000
node_addr = '/mnt/node_address'

[executor_evm]
enable_metrics = true
executor_port = 50002
metrics_port = 60002

[storage_rocksdb]
crypto_port = 50005
enable_metrics = true
metrics_port = 60003
storage_port = 50003

[genesis_block]
prevhash = '0x0000000000000000000000000000000000000000000000000000000000000000'
timestamp = 1672284552735

[system_config]
admin = '9bab5858df4a9e84ff3958884a01a4fce5e07edb'
block_interval = 3
block_limit = 100
chain_id = 'c57bf69f92e8a473ae58582fbf3dc547e1e78c3442bb4bf3313b7005b4163466'
quota_limit = 1073741824
validators = [
    'b5fb8f3afe21956fe64ddc7b226e4663aa65b933',
    'f76b5aa185a214f489c4a9dee47472712ff6d968',
    '0b6227e744854b3fa4593e657a19a3cf56605750',
]
version = 0

[controller]
consensus_port = 50001
controller_port = 50004
crypto_port = 50005
enable_metrics = true
executor_port = 50002
metrics_port = 60004
network_port = 50000
node_address = '/mnt/node_address'
storage_port = 50003
validator_address_len = 20

[crypto_sm]
crypto_port = 50005
enable_metrics = true
metrics_port = 60005

