account = "99a82d112940cfffa95182921fe6e8a1fd8b8539"
enable_metrics = true
is_danger = false
log_level = "info"
network_listen_port = 40000

[cloud_storage]
access_key_id = ""
bucket = ""
endpoint = ""
secret_access_key = ""

[grpc_ports]
consensus_port = 50001
controller_port = 50004
executor_port = 50002
network_port = 50000
storage_port = 50003

[metrics_ports]
consensus_metrics_port = 60001
controller_metrics_port = 60004
executor_metrics_port = 60002
network_metrics_port = 60000
storage_metrics_port = 60003

