apiVersion: v1
kind: ConfigMap
binaryData:
  private_key: MzZkNjFmMDliNzQ1YTRkYTk0ZTc1OTA0YjJiZWNhNDkxZGNhMmE3ZDdiYzBiYzgzYTJkN2E4N2QxYTkwYzk4MA==
data:
  node_address: cb34cf78489a17205529113b0df10b8080e5259e
  validator_address: cb34cf78489a17205529113b0df10b8080e5259e
metadata:
  labels:
    app.kubernetes.io/chain-name: sla-bft
    app.kubernetes.io/chain-node: sla-bft-node2
  name: sla-bft-node2-account
