apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/chain-name: sla-raft
    app.kubernetes.io/chain-node: sla-raft-node0
  name: sla-raft-node0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/chain-name: sla-raft
      app.kubernetes.io/chain-node: sla-raft-node0
  serviceName: ''
  template:
    metadata:
      labels:
        app.kubernetes.io/chain-name: sla-raft
        app.kubernetes.io/chain-node: sla-raft-node0
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/chain-name
                  operator: In
                  values:
                  - sla-raft
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - network
        - run
        - -c
        - /etc/cita-cloud/config/config.toml
        - -l
        - /etc/cita-cloud/log/network-log4rs.yaml
        image: registry.devops.rivtower.com/cita-cloud/network_zenoh:v6.6.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - grpc_health_probe
            - -addr=127.0.0.1:50000
          initialDelaySeconds: 30
          periodSeconds: 10
        name: network
        ports:
        - containerPort: 40000
          name: network
          protocol: UDP
        - containerPort: 50000
          name: grpc
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: 120m
            memory: 240Mi
        volumeMounts:
        - mountPath: /data
          name: datadir
        - mountPath: /etc/cita-cloud/config
          name: node-config
        - mountPath: /etc/cita-cloud/log
          name: node-log
        - mountPath: /mnt
          name: node-account
        workingDir: /data
      - command:
        - consensus
        - run
        - -c
        - /etc/cita-cloud/config/config.toml
        - --stdout
        image: registry.devops.rivtower.com/cita-cloud/consensus_raft:v6.6.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - grpc_health_probe
            - -addr=127.0.0.1:50001
          initialDelaySeconds: 30
          periodSeconds: 10
        name: consensus
        ports:
        - containerPort: 50001
          name: grpc
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: 120m
            memory: 240Mi
        volumeMounts:
        - mountPath: /data
          name: datadir
        - mountPath: /etc/cita-cloud/config
          name: node-config
        - mountPath: /etc/cita-cloud/log
          name: node-log
        - mountPath: /mnt
          name: node-account
        workingDir: /data
      - command:
        - executor
        - run
        - -c
        - /etc/cita-cloud/config/config.toml
        - -l
        - /etc/cita-cloud/log/executor-log4rs.yaml
        image: registry.devops.rivtower.com/cita-cloud/executor_evm:v6.6.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - grpc_health_probe
            - -addr=127.0.0.1:50002
          initialDelaySeconds: 30
          periodSeconds: 10
        name: executor
        ports:
        - containerPort: 50002
          name: grpc
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: 120m
            memory: 240Mi
        volumeMounts:
        - mountPath: /data
          name: datadir
        - mountPath: /etc/cita-cloud/config
          name: node-config
        - mountPath: /etc/cita-cloud/log
          name: node-log
        workingDir: /data
      - command:
        - storage
        - run
        - -c
        - /etc/cita-cloud/config/config.toml
        - -l
        - /etc/cita-cloud/log/storage-log4rs.yaml
        image: registry.devops.rivtower.com/cita-cloud/storage_rocksdb:v6.6.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - grpc_health_probe
            - -addr=127.0.0.1:50003
          initialDelaySeconds: 30
          periodSeconds: 10
        name: storage
        ports:
        - containerPort: 50003
          name: grpc
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: 120m
            memory: 240Mi
        volumeMounts:
        - mountPath: /data
          name: datadir
        - mountPath: /etc/cita-cloud/config
          name: node-config
        - mountPath: /etc/cita-cloud/log
          name: node-log
        workingDir: /data
      - command:
        - controller
        - run
        - -c
        - /etc/cita-cloud/config/config.toml
        - -l
        - /etc/cita-cloud/log/controller-log4rs.yaml
        image: registry.devops.rivtower.com/cita-cloud/controller:v6.6.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - grpc_health_probe
            - -addr=127.0.0.1:50004
          initialDelaySeconds: 60
          periodSeconds: 10
        name: controller
        ports:
        - containerPort: 50004
          name: grpc
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: 120m
            memory: 240Mi
        volumeMounts:
        - mountPath: /data
          name: datadir
        - mountPath: /etc/cita-cloud/config
          name: node-config
        - mountPath: /etc/cita-cloud/log
          name: node-log
        - mountPath: /mnt
          name: node-account
        workingDir: /data
      - command:
        - crypto
        - run
        - -c
        - /etc/cita-cloud/config/config.toml
        - -l
        - /etc/cita-cloud/log/crypto-log4rs.yaml
        - -p
        - /mnt/private_key
        image: registry.devops.rivtower.com/cita-cloud/crypto_sm:v6.6.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - grpc_health_probe
            - -addr=127.0.0.1:50005
          initialDelaySeconds: 30
          periodSeconds: 10
        name: crypto
        ports:
        - containerPort: 50005
          name: grpc
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: 120m
            memory: 240Mi
        volumeMounts:
        - mountPath: /data
          name: datadir
        - mountPath: /etc/cita-cloud/config
          name: node-config
        - mountPath: /etc/cita-cloud/log
          name: node-log
        - mountPath: /mnt
          name: node-account
        workingDir: /data
      hostAliases:
      - hostnames:
        - sla-raft-node0
        ip: 0.0.0.0
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      volumes:
      - configMap:
          name: sla-raft-node0-account
        name: node-account
      - configMap:
          name: sla-raft-node0-config
        name: node-config
      - configMap:
          name: sla-raft-node0-log
        name: node-log
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: ceph-filesystem
